---
abstract: 'Bootloader host software for Microchip PIC devices'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  IO::Select: 0
  Test::Exception: 0
  Test::More: 0
  Test::Requires: 0
  Test::SharedFork: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Microchip-Bootloader
requires:
  Carp: 0
  Data::Dumper: 0
  Device::SerialPort: 0
  Digest::CRC: 0
  Fcntl: 0
  Getopt::Std: 0
  IO::Socket::INET: 0
  Moose: 0
  Pod::Help: 0
  Symbol: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.012
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/hollie/device-microchip-bootloader/issues
  repository: git://github.com/hollie/device-microchip-bootloader.git
version: 0.2
